//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsultationRO()
        {
            this.Consultations = new HashSet<Consultation>();
        }
    
        public long consultationRosID { get; set; }
        public Nullable<long> patientID { get; set; }
        public Nullable<long> systemItemID { get; set; }
        public string cb { get; set; }
        public Nullable<System.DateTime> cd { get; set; }
        public Nullable<System.DateTime> mb { get; set; }
        public string md { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual SystemItemss SystemItemss { get; set; }
    }
}
