//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSpeciality
    {
        public long doctorSpecialityID { get; set; }
        public string specialityName { get; set; }
        public Nullable<long> doctorID { get; set; }
        public string CB { get; set; }
        public string MB { get; set; }
        public Nullable<System.DateTime> CD { get; set; }
        public Nullable<System.DateTime> MD { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
