//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorLicenseState
    {
        public long doctorLicenseStateID { get; set; }
        public Nullable<long> doctorID { get; set; }
        public string stateName { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
