//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyHX
    {
        public long fhxid { get; set; }
        public Nullable<long> questionID { get; set; }
        public string answer { get; set; }
        public Nullable<long> patientID { get; set; }
        public string customQuestion { get; set; }
        public string customAnswer { get; set; }
        public string cb { get; set; }
        public Nullable<System.DateTime> cd { get; set; }
        public string mb { get; set; }
        public Nullable<System.DateTime> md { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Question Question { get; set; }
    }
}
