//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public long medicationID { get; set; }
        public string medicineName { get; set; }
        public string frequency { get; set; }
        public string source { get; set; }
        public Nullable<long> patientId { get; set; }
        public string cb { get; set; }
        public Nullable<System.DateTime> cd { get; set; }
        public string mb { get; set; }
        public Nullable<System.DateTime> md { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> reportedDate { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
